### PR TITLE
Fix error due to missing optionMenu

### PR DESCRIPTION
**Pull request by stefanocoretta**
Hello! I think this in an issue with a recent Praat version, but when I run the Tools... > Extract vowels from textgrids I get this error.

Screenshot 2024-02-05 at 16 33 34

This can be fixed by adding `optionMenu: "", 1`, hence the PR. :)

### CODE REVIEW

**Comment by santiagobarreda** [comment]
Sorry I don't even know what I did above, I was trying to resolve a merge conflict and then I apparently did something else. I just downloaded the newest version of Praat and don't get any error with the code as it is. Also in your code you were not only adding a 1 but also adding a drop down text box which seemed to duplicate what was above already. Sorry I might be a bit confused.

**Comment by stefanocoretta** [comment]
Hi! No problem. In my case, the script did not work because it did not like this part in `Fast Track/functions/tools/extractVowelswithTG.praat`:

```
    optionMenu: "", 1
    option: "[Click to Read]"
    option: "This assumes the final symbol on the vowel labels is used to indicate stress."
    option: "Indicate which stress symbols you want to extract (leave blank for no symbols)"
    sentence: "Stress to extract", stress_to_extract$
    option: "[Click to Read]"
```

It complained that the last `option` was not under an `optionMenu` (because of the `sentence`).

I will try to run this again making sure everything on my end is up to date and let you know. :)

**Comment by stefanocoretta** [comment]
PS I just noticed you might have committed changes to my fork (no problem, I will fix that, but I am surprised GH let you do that!)

**Comment by stefanocoretta** [comment]
Ok! Never mind, I deleted and reinstalled Praat, redownloaded the FastTrack repo and re-added the buttons and now it works. :) Not sure what happened there! Sorry for the bother!

**Comment by santiagobarreda** [comment]
To be honest, I don't even know what I did, some aspects of github remain a mystery. It said there was a merge conflict, I went to resolve it and hit ok. Next thing I know it said I merged something into something else and there were many changes, but I saw no changes on the local master branch. As you said, I didn't even know it was possible that I could do that on your fork (sorry!), I thought I was only resolving the merge conflict on the single file.

**Pull request closed without merging**
